name: New_App

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repo Name (e.g. MyRepo)'
        required: true
        default: ''
      repo_description:
        description: 'Repo Description'
        required: false
        default: ''
      template_repo:
        description: 'Template Repo Name'
        required: false
        default: 'template-gendloopAppR'
        type: choice
        options:
          - 'template-gendloopAppR'
          - 'template-gendloopApp'
          - 'template-gendloopAppV'

jobs:
  new_app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3

      - name: create-repo-by-template
        uses: gendloop/create-repo-by-template@v1.0.0
        with:
          token: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}
          template_repo: ${{ inputs.template_repo }}
          repo_name: ${{ inputs.repo_name }}
          repo_description: ${{ inputs.repo_description }}

      - name: copy-secrets-to-repo
        uses: gendloop/copy-secrets@v1.0.0
        with:
          repo: ${{ inputs.repo_name }}
          repo_owner: ${{ github.actor }}
          token: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}
          secret_names: 'GENDLOOP_ACCESS_TOKEN'
          secret_values: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}

      - name: add-topics-for-repo
        uses: gendloop/replace-repo-topics@v1.0.0
        with:
          token: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}
          repo: ${{ inputs.repo_name }}
          topics: '"app"'

      - name: get-time
        run: |
          echo "CURRENT_TIME=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
          echo $CURRENT_TIME

      - name: record-run-time
        run: |
          file="log.md"
          if [ -f $file ]; then
            echo "$file already exists";
          else
            echo "" > $file;
            echo "create new file: $file";
          fi
          sed -i "1s/^/$(echo "${CURRENT_TIME}: run workflow " | sed 's/\//\\\//g')\`${{ github.workflow }}\` \n\n/" $file

      - name: git-push
        uses: gendloop/git-push@v1.0.0
        with:
          token: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}
          commit: "chore: run workflow \\`${{ github.workflow }}\\` "
